import React, { useEffect, useRef, useState } from 'react';

// Estimates and appointments are handled on the shop's CARWISE profile.
const CARWISE_URL =
  'https://www.carwise.com/auto-body-shops/williamson-collision-center-miami-fl-33157/465414';

// The site deploys under a base path (/collision-center/), so public-folder
// assets can't be referenced with root-absolute URLs.
const withBase = <T extends Record<string, string>>(paths: T): T =>
  Object.fromEntries(
    Object.entries(paths).map(([key, p]) => [key, import.meta.env.BASE_URL + p.replace(/^\//, '')])
  ) as T;

// Optimized WebP assets generated by scripts/optimize-images.mjs from the
// originals in assets-source/ (which are not deployed).
const IMG = withBase({
  heroBg: '/images/opt/hero-bg-1920.webp',
  heroBgSm: '/images/opt/hero-bg-1280.webp',
  facadeFront: '/images/opt/facade-front-1200.webp',
  facadeAerial: '/images/opt/facade-aerial-1200.webp',
  reception: '/images/opt/reception-1600.webp',
  receptionThumb: '/images/opt/reception-480.webp',
  serviceDrive: '/images/opt/service-drive-1600.webp',
  serviceDriveThumb: '/images/opt/service-drive-480.webp',
  entrance: '/images/opt/entrance-1600.webp',
  frameRackWide: '/images/opt/frame-rack-wide-1600.webp',
  shopOverview: '/images/opt/shop-overview-1600.webp',
  shopOverviewThumb: '/images/opt/shop-overview-480.webp',
  frameRackCarOLiner: '/images/opt/frame-rack-caroliner-1600.webp',
  frameRackCarOLinerThumb: '/images/opt/frame-rack-caroliner-480.webp',
  paintMixRoom: '/images/opt/paint-mix-room-1600.webp',
  paintMixRoomThumb: '/images/opt/paint-mix-room-480.webp',
  paintBench: '/images/opt/paint-bench-1600.webp',
  paintBenchThumb: '/images/opt/paint-bench-480.webp',
  escaladeBumper: '/images/opt/escalade-bumper-1600.webp',
  escaladeBumperThumb: '/images/opt/escalade-bumper-480.webp',
  escaladeMasked: '/images/opt/escalade-masked-1600.webp',
  escaladeMaskedThumb: '/images/opt/escalade-masked-480.webp',
  teamWarehouse: '/images/opt/team-warehouse-1600.webp',
  teamWarehouseThumb: '/images/opt/team-warehouse-480.webp',
  bodyTechStaff: '/images/opt/body-tech-staff-1200.webp',
  officeStaff: '/images/opt/office-staff-1200.webp',
  paintShopStaff: '/images/opt/paint-shop-staff-1200.webp',
});

const LOGO = withBase({
  brandWhite: '/images/opt/wordmark-white.webp',
  brandBlack: '/images/opt/wordmark-black.webp',
  alfaRomeo: '/images/opt/alfa-romeo-certified.webp',
  cpn: '/images/opt/cpn.webp',
  hyundai: '/images/opt/hyundai-recognized.webp',
  kia: '/images/opt/kia-certified.webp',
  nissanInfiniti: '/images/opt/nissan-infiniti.webp',
  fca: '/images/opt/fca.webp',
  jeep: '/images/opt/jeep.webp',
  ram: '/images/opt/ram.webp',
  dodge: '/images/opt/dodge.webp',
  chrysler: '/images/opt/chrysler.webp',
  fiat: '/images/opt/fiat.webp',
  cadillac: '/images/opt/cadillac.webp',
  chevrolet: '/images/opt/chevrolet.webp',
  buick: '/images/opt/buick.webp',
  gmc: '/images/opt/gmc.webp',
  icarGold: '/images/opt/icar-gold.webp',
  // ASE / AATI badges: add the source PNGs to assets-source/images/Williamson/,
  // list them in scripts/optimize-images.mjs, then restore the <img> tags in BrandStrip.
});

function useScrollReveal() {
  useEffect(() => {
    const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const elements = Array.from(document.querySelectorAll<HTMLElement>('.reveal'));

    if (prefersReducedMotion) {
      elements.forEach((el) => el.classList.add('is-visible'));
      return;
    }

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-visible');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.12, rootMargin: '0px 0px -60px 0px' }
    );

    elements.forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, []);
}

const NAV_HEIGHT = 90;

const NAV_LINKS = [
  { label: 'Services', href: '#services' },
  { label: 'Certifications', href: '#certifications' },
  { label: 'Facility', href: '#facility' },
  { label: 'Team', href: '#team' },
  { label: 'FAQ', href: '#faq' },
  { label: 'Location & Hours', href: '#location' },
];

function Navbar() {
  const [menuOpen, setMenuOpen] = useState(false);
  // compact: solid background + smaller logo once the page is scrolled.
  // hidden: slides away while scrolling down, reappears on any scroll up,
  // so the phone number and Schedule CTA are always one flick away.
  const [compact, setCompact] = useState(false);
  const [hidden, setHidden] = useState(false);

  useEffect(() => {
    let lastY = window.scrollY;
    let ticking = false;
    const onScroll = () => {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(() => {
        const y = window.scrollY;
        setCompact(y > 40);
        setHidden(y > 560 && y > lastY + 2);
        lastY = y;
        ticking = false;
      });
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  // Lock body scroll while the mobile menu is open; close it on Escape.
  useEffect(() => {
    document.body.style.overflow = menuOpen ? 'hidden' : '';
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setMenuOpen(false);
    };
    window.addEventListener('keydown', onKey);
    return () => {
      document.body.style.overflow = '';
      window.removeEventListener('keydown', onKey);
    };
  }, [menuOpen]);

  const linkBase =
    'font-headline font-bold tracking-tighter uppercase px-3 py-2 cursor-pointer text-sm transition-colors duration-300';
  const linkColor = 'text-paper hover:text-primary-container';

  return (
    <>
      <nav
        className={`fixed top-0 inset-x-0 z-50 transition-all duration-500 ${hidden ? '-translate-y-full' : 'translate-y-0'} ${compact ? 'bg-background/95 backdrop-blur-md shadow-lg shadow-black/25' : 'bg-transparent'}`}
        style={{ height: compact ? 72 : NAV_HEIGHT }}
      >
        <div className="relative h-full flex justify-between items-center w-full px-4 sm:px-6 lg:px-8 max-w-none gap-4">
          <a
            className="shrink-0 inline-flex items-center overflow-hidden h-[4.5rem] sm:h-16 lg:h-20"
            href="#"
            aria-label="Williamson Collision Center home"
          >
            <img
              src={LOGO.brandWhite}
              alt="Williamson Collision Center · GM Certified"
              className={`w-auto max-w-[72vw] object-contain object-left transition-all duration-500 ${compact ? 'h-14 sm:h-14 lg:h-16' : 'h-24 sm:h-24 lg:h-[7.5rem]'}`}
              loading="eager"
              decoding="async"
            />
          </a>

          <div className="hidden md:flex items-center gap-5 xl:gap-8">
            {NAV_LINKS.map((l) => (
              <a key={l.href} className={`${linkBase} ${linkColor}`} href={l.href}>{l.label}</a>
            ))}
          </div>

          <div className="flex items-center gap-6">
            <a
              aria-label="Call Williamson-Collision"
              href="tel:+13052388801"
              className="hidden lg:inline-flex items-center gap-2 transition-colors font-label text-xs tracking-widest-custom uppercase text-paper/80 hover:text-primary-container"
            >
              <span className="material-symbols-outlined text-base">call</span>
              305-238-8801
            </a>
            <a
              className="hidden lg:inline-flex font-headline font-bold uppercase tracking-tighter px-6 py-3 transition-all duration-500 ease-in-out cursor-pointer active:opacity-80 bg-primary-container text-on-primary-container hover:bg-white"
              href={CARWISE_URL}
              target="_blank"
              rel="noopener noreferrer"
            >
              SCHEDULE REPAIR
            </a>
            <button
              type="button"
              className="md:hidden text-paper p-1 -mr-1"
              aria-label="Open menu"
              aria-expanded={menuOpen}
              onClick={() => setMenuOpen(true)}
            >
              <span className="material-symbols-outlined text-4xl">menu</span>
            </button>
          </div>
        </div>
      </nav>

      {/* Mobile full-screen menu */}
      {menuOpen && (
        <div className="fixed inset-0 z-[60] md:hidden anim-fade-in" role="dialog" aria-modal="true" aria-label="Menu">
          <div className="absolute inset-0 bg-background/97 backdrop-blur-sm"></div>
          <div className="relative h-full flex flex-col">
            <div className="flex items-center justify-between px-4 sm:px-6" style={{ height: NAV_HEIGHT }}>
              <img
                src={LOGO.brandWhite}
                alt="Williamson Collision Center"
                className="h-16 w-auto max-w-[64vw] object-contain object-left"
              />
              <button
                type="button"
                className="text-paper p-1 -mr-1"
                aria-label="Close menu"
                onClick={() => setMenuOpen(false)}
              >
                <span className="material-symbols-outlined text-4xl">close</span>
              </button>
            </div>

            <nav className="flex-1 flex flex-col justify-center px-6 sm:px-8">
              {NAV_LINKS.map((l) => (
                <a
                  key={l.href}
                  href={l.href}
                  onClick={() => setMenuOpen(false)}
                  className="group flex items-center justify-between border-b border-outline-variant/20 py-4 text-on-background hover:text-primary-container transition-colors"
                >
                  <span className="font-headline text-3xl sm:text-4xl font-extrabold uppercase tracking-tighter leading-none">{l.label}</span>
                  <span className="material-symbols-outlined text-on-surface-variant group-hover:text-primary-container transition-colors">arrow_forward</span>
                </a>
              ))}
            </nav>

            <div className="px-6 sm:px-8 pb-10 pt-4 flex flex-col gap-3">
              <a
                href="tel:+13052388801"
                onClick={() => setMenuOpen(false)}
                className="flex items-center justify-center gap-2 border border-outline-variant/40 py-4 font-headline font-bold uppercase tracking-tighter text-paper hover:border-primary-container hover:text-primary-container transition-colors"
              >
                <span className="material-symbols-outlined text-lg">call</span>
                305-238-8801
              </a>
              <a
                href={CARWISE_URL}
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => setMenuOpen(false)}
                className="flex items-center justify-center py-4 bg-primary-container text-on-primary-container font-headline font-bold uppercase tracking-tighter hover:bg-white transition-colors"
              >
                Schedule Repair
              </a>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

function Hero() {
  return (
    <section data-tone="dark" className="relative w-full h-[88vh] min-h-[560px] md:h-[860px] md:min-h-[640px] flex items-center overflow-hidden bg-background">
      {/* Full-bleed hero image covers the entire section */}
      <div className="absolute inset-0 z-0">
        <img
          alt="Williamson-Collision technicians repairing a Cadillac SUV inside the Miami facility"
          className="w-full h-full object-cover object-center anim-fade-in"
          src={IMG.heroBg}
          srcSet={`${IMG.heroBgSm} 1280w, ${IMG.heroBg} 1920w`}
          sizes="100vw"
          loading="eager"
          decoding="async"
          fetchPriority="high"
        />
        {/* Left-anchored vignette keeps headline copy legible while letting the photo breathe on the right */}
        <div className="absolute inset-0 bg-gradient-to-r from-background/85 via-background/35 to-transparent"></div>
        {/* Soft floor + ceiling vignette so the section integrates with the navbar above and the BrandStrip below */}
        <div className="absolute inset-0 bg-gradient-to-t from-background/45 via-transparent to-background/15"></div>
      </div>

      <div className="relative z-10 w-full max-w-7xl mx-auto px-5 sm:px-8 md:px-12">
        <div className="max-w-3xl">
          <p className="font-label text-xs tracking-widest-custom uppercase text-primary-container mb-6 border-l-2 border-primary-container pl-4 anim-fade-up" style={{ animationDelay: '0.15s' }}>
            The Body Shop of Williamson Automotive &middot; South Miami
          </p>
          <h1 className="font-headline text-5xl md:text-7xl font-extrabold uppercase tracking-tighter leading-[0.9] mb-8 anim-fade-up text-on-background" style={{ animationDelay: '0.3s' }}>
            Williamson Automotive<br/>
            <span className="text-primary-container">Collision</span> <span className="text-on-surface-variant">Center.</span>
          </h1>
          <p className="font-body text-base text-on-surface-variant max-w-xl mb-10 anim-fade-up" style={{ animationDelay: '0.45s' }}>
            The authorized, factory-certified body shop of Williamson Automotive. OEM-trained technicians, genuine parts, and a fully tooled Car-O-Liner facility, serving every Cadillac, GMC, Buick, Chevrolet, Stellantis, Nissan, Infiniti, Hyundai, and Kia driver in Miami-Dade.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 anim-fade-up" style={{ animationDelay: '0.55s' }}>
            <a className="inline-flex justify-center items-center px-8 py-4 bg-primary-container text-on-primary-container font-headline font-bold uppercase tracking-widest-custom text-sm hover:bg-white transition-all duration-700 ease-in-out group" href={CARWISE_URL} target="_blank" rel="noopener noreferrer">
              Get an Estimate
              <span className="material-symbols-outlined ml-3 text-lg group-hover:translate-x-1 transition-transform">arrow_forward</span>
            </a>
            <a className="inline-flex justify-center items-center px-8 py-4 bg-transparent border border-on-surface-variant/60 text-on-background font-headline font-bold uppercase tracking-widest-custom text-sm hover:border-primary-container hover:text-primary-container transition-all duration-700 ease-in-out" href={CARWISE_URL} target="_blank" rel="noopener noreferrer">
              Schedule Appointment
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}

type BadgeTile =
  | { kind: 'image'; src: string; alt: string; name: string }
  | { kind: 'text'; name: string; tagline: string };

function BadgeCard({ tile }: { tile: BadgeTile }) {
  return (
    <div className="group relative aspect-square bg-paper-card flex flex-col items-center justify-center p-4 md:p-5 shadow-[0_18px_38px_-22px_rgba(15,15,15,0.35)] ring-1 ring-paper-line hover:ring-accent-deep hover:-translate-y-1 transition-all duration-500 overflow-hidden">
      {/* subtle gold corner mark */}
      <div className="absolute top-0 left-0 w-6 h-6 border-t border-l border-accent-deep/0 group-hover:border-accent-deep/80 transition-colors duration-500"></div>
      <div className="absolute bottom-0 right-0 w-6 h-6 border-b border-r border-accent-deep/0 group-hover:border-accent-deep/80 transition-colors duration-500"></div>

      {tile.kind === 'image' ? (
        <>
          <div className="flex-1 w-full flex items-center justify-center min-h-0">
            <img
              src={tile.src}
              alt={tile.alt}
              className="max-h-[78%] max-w-full w-auto object-contain group-hover:scale-[1.04] transition-transform duration-500"
              loading="lazy"
            />
          </div>
          <div className="mt-2 font-label text-[9px] tracking-widest-custom uppercase text-ink-faint text-center w-full truncate">
            {tile.name}
          </div>
        </>
      ) : (
        <div className="flex flex-col items-center justify-center h-full text-center">
          <span className="material-symbols-outlined text-3xl text-accent-deep mb-3">verified</span>
          <div className="font-headline text-lg md:text-xl font-extrabold tracking-tight uppercase text-ink leading-[1]">
            {tile.name}
          </div>
          <div className="mt-2 font-label text-[9px] tracking-widest-custom uppercase text-ink-faint">
            {tile.tagline}
          </div>
        </div>
      )}
    </div>
  );
}

function FamilyPanel({
  eyebrow,
  title,
  blurb,
  tiles,
  cols,
}: {
  eyebrow: string;
  title: string;
  blurb: string;
  tiles: BadgeTile[];
  cols: string;
}) {
  return (
    <div className="relative border border-paper-line bg-paper-card p-6 md:p-8 reveal">
      <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-6 md:mb-8">
        <div>
          <div className="font-label text-[10px] tracking-widest-custom uppercase text-accent-deep mb-2">{eyebrow}</div>
          <h3 className="font-headline text-2xl md:text-3xl font-bold uppercase tracking-tight text-ink">{title}</h3>
        </div>
        <p className="font-body text-xs md:text-sm text-ink-muted max-w-md leading-relaxed">{blurb}</p>
      </div>

      <div className={`grid gap-3 md:gap-4 ${cols}`}>
        {tiles.map((t) => (
          <div key={t.name} className="contents">
            <BadgeCard tile={t} />
          </div>
        ))}
      </div>
    </div>
  );
}

function BrandStrip() {
  const stellantis: BadgeTile[] = [
    { kind: 'image', src: LOGO.fca, alt: 'FCA US LLC Certified Collision Repair Center', name: 'FCA US LLC' },
    { kind: 'image', src: LOGO.jeep, alt: 'Jeep Certified Collision Center', name: 'Jeep' },
    { kind: 'image', src: LOGO.ram, alt: 'Ram Certified Collision Center', name: 'Ram' },
    { kind: 'image', src: LOGO.dodge, alt: 'Dodge Certified Collision Center', name: 'Dodge' },
    { kind: 'image', src: LOGO.chrysler, alt: 'Chrysler Certified Collision Center', name: 'Chrysler' },
    { kind: 'image', src: LOGO.fiat, alt: 'Fiat Certified Collision Center', name: 'Fiat' },
    { kind: 'image', src: LOGO.alfaRomeo, alt: 'Alfa Romeo Certified Collision Center', name: 'Alfa Romeo' },
  ];
  const asian: BadgeTile[] = [
    { kind: 'image', src: LOGO.hyundai, alt: 'Hyundai Recognized Collision Repair Center', name: 'Hyundai · Recognized' },
    { kind: 'image', src: LOGO.kia, alt: 'Kia Certified Collision Repair Center', name: 'Kia · Certified' },
    { kind: 'image', src: LOGO.nissanInfiniti, alt: 'Nissan & Infiniti Certified Repair Network', name: 'Nissan & Infiniti' },
  ];
  const gm: BadgeTile[] = [
    { kind: 'image', src: LOGO.cadillac, alt: 'Cadillac', name: 'Cadillac' },
    { kind: 'image', src: LOGO.chevrolet, alt: 'Chevrolet', name: 'Chevrolet' },
    { kind: 'image', src: LOGO.buick, alt: 'Buick', name: 'Buick' },
    { kind: 'image', src: LOGO.gmc, alt: 'GMC', name: 'GMC' },
    { kind: 'text', name: 'Aluminum', tagline: 'Certified Repair' },
  ];

  return (
    <section id="certifications" data-tone="light" className="py-16 md:py-32 bg-paper relative overflow-hidden">
      {/* Soft gold washes for warmth without darkening the paper tone */}
      <div className="absolute -top-20 -left-40 w-[700px] h-[700px] bg-accent-deep/[0.06] rounded-full blur-[160px] pointer-events-none"></div>
      <div className="absolute -bottom-20 right-0 w-[500px] h-[500px] bg-accent-deep/[0.04] rounded-full blur-[140px] pointer-events-none"></div>
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-accent-deep/40 to-transparent pointer-events-none"></div>

      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12 relative z-10">
        {/* HEADER */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-end mb-14 md:mb-16">
          <div className="lg:col-span-7 reveal reveal-left">
            <p className="font-label text-xs tracking-widest-custom uppercase text-accent-deep mb-5 border-l-2 border-accent-deep pl-4">
              Certified. Trusted. Preferred.
            </p>
            <h2 className="font-headline text-4xl md:text-6xl font-extrabold uppercase tracking-tighter text-ink leading-[0.95]">
              Factory-Certified.<br/>
              <span className="text-accent-deep">Quality Guaranteed.</span>
            </h2>
          </div>
          <div className="lg:col-span-5 reveal reveal-right">
            <p className="font-body text-sm md:text-base text-ink-muted leading-relaxed mb-6">
              As the authorized Collision Repair Center for <span className="font-headline font-bold uppercase tracking-tight text-ink">Williamson Automotive</span>, we&apos;re factory-certified by every manufacturer in our showroom, and many more. Our team follows strict OEM repair standards, uses genuine parts, and relies on advanced, properly calibrated equipment to ensure your vehicle is restored safely and your warranty remains protected.
            </p>
            <p className="font-headline text-xs md:text-sm font-bold uppercase tracking-tight text-ink mb-6 flex flex-wrap items-center gap-x-2 gap-y-1">
              <span>15+ Brands</span>
              <span className="text-accent-deep">&ndash;</span>
              <span>Certified Aluminum Repair</span>
              <span className="text-accent-deep">&ndash;</span>
              <span>I-Car Trained &amp; Certified Technicians</span>
            </p>
            <div className="grid grid-cols-3 gap-px bg-paper-line">
              {[
                { stat: '15+', label: 'Brand Certifications' },
                { stat: '1', label: 'Aluminum Bay' },
                { stat: '100%', label: 'OEM Parts' },
              ].map((s) => (
                <div key={s.label} className="bg-paper-card px-3 py-4 text-center">
                  <div className="font-headline text-2xl md:text-3xl font-extrabold text-accent-deep leading-none">{s.stat}</div>
                  <div className="mt-2 font-label text-[9px] tracking-widest-custom uppercase text-ink-muted">{s.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* FAMILY PANELS */}
        <div className="grid grid-cols-1 gap-6">
          <FamilyPanel
            eyebrow="General Motors"
            title="Part of the GM Collision Repair Network (GMCRN)"
            blurb="The Williamson family&apos;s home brands plus the aluminum certification required for modern luxury and full-size trucks. This designation allows us to order aluminum and structural parts and components that are not sold to non-Certified Repair Centers."
            tiles={gm}
            cols="grid-cols-2 sm:grid-cols-3 md:grid-cols-5"
          />

          <FamilyPanel
            eyebrow="Stellantis Group"
            title="Stellantis · FCA US LLC"
            blurb="Full FCA US LLC Certified Collision Repair Center status. Mopar parts, official tooling, and certified procedures across every Stellantis brand."
            tiles={stellantis}
            cols="grid-cols-3 sm:grid-cols-4 md:grid-cols-7"
          />

          <FamilyPanel
            eyebrow="Asian Imports"
            title="Imported Manufacturers"
            blurb="Recognized by Hyundai, certified by Kia, and part of the Nissan &amp; Infiniti Certified Repair Network."
            tiles={asian}
            cols="grid-cols-1 sm:grid-cols-3"
          />
        </div>

        {/* TECHNICIAN & SHOP CERTIFICATIONS */}
        <div className="mt-6 flex flex-col md:flex-row md:items-center gap-6 md:gap-10 bg-paper-card border border-paper-line px-6 md:px-8 py-6 reveal">
          <div className="md:max-w-[14rem]">
            <div className="font-label text-[10px] tracking-widest-custom uppercase text-accent-deep mb-2">Shop &amp; Technician</div>
            <div className="font-headline text-sm md:text-base font-bold tracking-tight uppercase text-ink leading-tight">I-Car Gold Class &middot; ASE &amp; AATI Certified Technicians</div>
          </div>
          <div className="flex flex-wrap items-center gap-x-8 gap-y-5 md:ml-auto">
            <img src={LOGO.icarGold} alt="I-CAR Gold Class certified collision repair shop" className="h-14 md:h-16 w-auto object-contain" loading="lazy" />
            {/* ASE & AATI logos: drop ASE-Certified.png / AATI-Certified.png into public/images/Williamson/ then restore these <img> tags */}
          </div>
        </div>

        {/* MEMBERSHIP STRIP */}
        <div className="mt-6 flex flex-col sm:flex-row items-center justify-between gap-6 bg-paper-card border border-paper-line px-6 md:px-8 py-5 reveal">
          <div className="flex items-center gap-5">
            <span className="material-symbols-outlined text-accent-deep">hub</span>
            <div>
              <div className="font-label text-[10px] tracking-widest-custom uppercase text-ink-faint">Active Member</div>
              <div className="font-headline text-sm md:text-base font-bold tracking-tight uppercase text-ink">Collision Performance Network</div>
            </div>
          </div>
          <img src={LOGO.cpn} alt="OEC Collision Performance Network" className="h-7 md:h-8 object-contain" />
          <a href="#services" className="inline-flex items-center gap-2 font-headline font-bold uppercase tracking-widest-custom text-xs text-ink hover:text-accent-deep transition-colors">
            See Our Services
            <span className="material-symbols-outlined text-base">arrow_forward</span>
          </a>
        </div>
      </div>
    </section>
  );
}

function ServicesBento() {
  return (
    <section id="services" data-tone="dark" className="py-20 md:py-32 bg-background relative overflow-hidden">
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[800px] bg-primary-container/10 rounded-full blur-[120px] pointer-events-none"></div>

      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12 relative z-10">
        <div className="mb-14 md:mb-20 grid grid-cols-1 md:grid-cols-12 gap-8 md:gap-10 items-end">
          <div className="md:col-span-7 reveal">
            <p className="font-label text-xs tracking-widest-custom uppercase text-primary-container mb-5 border-l-2 border-primary-container pl-4">Signature Services</p>
            <h2 className="font-headline text-4xl md:text-6xl font-extrabold uppercase tracking-tighter text-on-background leading-[0.95]">
              Everything Your <br/><span className="text-on-surface-variant">Vehicle Needs.</span>
            </h2>
          </div>
          <p className="md:col-span-5 font-body text-sm md:text-base text-on-surface-variant max-w-md leading-relaxed pb-1 reveal reveal-delay-2">
            From frame straightening to color-matched refinish. Every operation happens under one roof, performed by technicians trained to manufacturer standards.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="group relative overflow-hidden bg-surface-container-lowest border border-outline-variant/30 min-h-[360px] md:min-h-[460px] md:col-span-2 hover:border-primary-container/50 transition-all duration-500 shadow-2xl shadow-black/40 reveal">
            <div className="absolute inset-0 z-0">
              <img alt="SUV on Car-O-Liner alignment rack during structural collision repair" className="w-full h-full object-cover opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" loading="lazy" decoding="async" src={IMG.frameRackWide} />
              <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/35 to-transparent"></div>
            </div>
            <div className="relative z-10 flex flex-col justify-end h-full p-10 md:p-12 translate-y-2 group-hover:translate-y-0 transition-transform duration-500">
              <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container mb-5 flex items-center gap-3"><span className="w-8 h-px bg-primary-container"></span>01 &nbsp;/&nbsp; Structural</span>
              <h3 className="font-headline text-3xl md:text-4xl font-bold uppercase tracking-tight text-on-background mb-4 max-w-md leading-[1.05]">Structural Collision Repair</h3>
              <p className="font-body text-sm text-on-surface-variant max-w-md leading-relaxed opacity-90 group-hover:opacity-100 transition-opacity duration-500">Laser-guided Car-O-Liner measuring systems return your vehicle&apos;s frame to factory tolerances down to the millimeter.</p>
            </div>
          </div>

          <div className="group relative overflow-hidden bg-surface-container-lowest border border-outline-variant/30 min-h-[360px] md:min-h-[460px] hover:border-primary-container/50 transition-all duration-500 shadow-2xl shadow-black/40 reveal reveal-delay-2">
            <div className="absolute inset-0 z-0">
              <img alt="Cadillac Escalade masked for paint inside the aluminum repair bay" className="w-full h-full object-cover opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" loading="lazy" decoding="async" src={IMG.escaladeMasked} />
              <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/35 to-transparent"></div>
            </div>
            <div className="relative z-10 flex flex-col justify-end h-full p-10 translate-y-2 group-hover:translate-y-0 transition-transform duration-500">
              <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container mb-5 flex items-center gap-3"><span className="w-8 h-px bg-primary-container"></span>02 &nbsp;/&nbsp; Aluminum</span>
              <h3 className="font-headline text-2xl md:text-3xl font-bold uppercase tracking-tight text-on-background mb-4 leading-[1.05]">Aluminum Body Repair</h3>
              <p className="font-body text-sm text-on-surface-variant max-w-sm leading-relaxed opacity-90 group-hover:opacity-100 transition-opacity duration-500">Isolated, contaminant-free bay with dedicated aluminum tooling. The certified way to repair modern Cadillac, Ram and Jeep bodies.</p>
            </div>
          </div>

          <div className="group relative overflow-hidden bg-surface-container-lowest border border-outline-variant/30 min-h-[320px] md:min-h-[400px] hover:border-primary-container/50 transition-all duration-500 shadow-2xl shadow-black/40 reveal reveal-delay-1">
            <div className="absolute inset-0 z-0">
              <img alt="In-house paint mixing room with full refinish toner library" className="w-full h-full object-cover opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" loading="lazy" decoding="async" src={IMG.paintMixRoom} />
              <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/35 to-transparent"></div>
            </div>
            <div className="relative z-10 flex flex-col justify-end h-full p-10 translate-y-2 group-hover:translate-y-0 transition-transform duration-500">
              <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container mb-5 flex items-center gap-3"><span className="w-8 h-px bg-primary-container"></span>03 &nbsp;/&nbsp; Refinish</span>
              <h3 className="font-headline text-2xl md:text-3xl font-bold uppercase tracking-tight text-on-background mb-4 leading-[1.05]">Paint &amp; Refinishing</h3>
              <p className="font-body text-sm text-on-surface-variant max-w-sm leading-relaxed opacity-90 group-hover:opacity-100 transition-opacity duration-500">Spectrophotometer-matched color, downdraft booths, multi-stage bake. An OEM finish, every panel.</p>
            </div>
          </div>

          <div className="group relative overflow-hidden bg-surface-container-lowest border border-outline-variant/30 min-h-[320px] md:min-h-[400px] md:col-span-2 hover:border-primary-container/50 transition-all duration-500 shadow-2xl shadow-black/40 reveal reveal-delay-2">
            <div className="absolute inset-0 z-0">
              <img alt="Replacement bumper test-fit on a Cadillac SUV during panel repair" className="w-full h-full object-cover opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" loading="lazy" decoding="async" src={IMG.escaladeBumper} />
              <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/35 to-transparent"></div>
            </div>
            <div className="relative z-10 flex flex-col justify-end h-full p-10 md:p-12 translate-y-2 group-hover:translate-y-0 transition-transform duration-500">
              <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container mb-5 flex items-center gap-3"><span className="w-8 h-px bg-primary-container"></span>04 &nbsp;/&nbsp; Panels</span>
              <h3 className="font-headline text-3xl md:text-4xl font-bold uppercase tracking-tight text-on-background mb-4 max-w-md leading-[1.05]">Body &amp; Panel Replacement</h3>
              <p className="font-body text-sm text-on-surface-variant max-w-md leading-relaxed opacity-90 group-hover:opacity-100 transition-opacity duration-500">OEM bumpers, fenders, hoods and quarters, fit, sealed and finished to factory drawings.</p>
            </div>
          </div>

          <div className="group relative overflow-hidden bg-surface-container-lowest border border-outline-variant/30 min-h-[320px] md:min-h-[400px] md:col-span-2 hover:border-primary-container/50 transition-all duration-500 shadow-2xl shadow-black/40 reveal reveal-delay-3">
            <div className="absolute inset-0 z-0">
              <img alt="Diagnostic and ADAS calibration bay" className="w-full h-full object-cover opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" loading="lazy" decoding="async" src={IMG.shopOverview} />
              <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/35 to-transparent"></div>
            </div>
            <div className="relative z-10 flex flex-col justify-end h-full p-10 md:p-12 translate-y-2 group-hover:translate-y-0 transition-transform duration-500">
              <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container mb-5 flex items-center gap-3"><span className="w-8 h-px bg-primary-container"></span>05 &nbsp;/&nbsp; Calibration</span>
              <h3 className="font-headline text-3xl md:text-4xl font-bold uppercase tracking-tight text-on-background mb-4 max-w-md leading-[1.05]">ADAS &amp; Glass</h3>
              <p className="font-body text-sm text-on-surface-variant max-w-md leading-relaxed opacity-90 group-hover:opacity-100 transition-opacity duration-500">OEM glass installation paired with full ADAS sensor recalibration so lane-keep, cruise and collision systems work as designed.</p>
            </div>
          </div>

          <a href={CARWISE_URL} target="_blank" rel="noopener noreferrer" className="group relative overflow-hidden bg-surface-container-lowest border border-outline-variant/30 min-h-[320px] md:min-h-[400px] hover:border-primary-container/60 transition-all duration-500 shadow-2xl shadow-black/40 reveal reveal-delay-4">
            <div className="absolute inset-0 z-0">
              <img alt="On-site Enterprise Rent-A-Car desk at the Williamson-Collision Center" className="w-full h-full object-cover opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" loading="lazy" decoding="async" src={IMG.entrance} />
              <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/40 to-transparent"></div>
            </div>
            <div className="relative z-10 flex flex-col justify-end h-full p-10 translate-y-2 group-hover:translate-y-0 transition-transform duration-500">
              <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container mb-5 flex items-center gap-3"><span className="w-8 h-px bg-primary-container"></span>06 &nbsp;/&nbsp; Rental</span>
              <h3 className="font-headline text-2xl md:text-3xl font-bold uppercase tracking-tight text-on-background mb-4 leading-[1.05]">On-Site Enterprise Rental</h3>
              <p className="font-body text-sm text-on-surface-variant max-w-sm leading-relaxed opacity-90 group-hover:opacity-100 transition-opacity duration-500">Drop the keys, pick up a rental. Enterprise Rent-A-Car operates a counter on our property. Insurance direct-bill ready.</p>
              <span className="mt-6 inline-flex items-center gap-2 font-label text-[10px] tracking-widest-custom uppercase text-on-background group-hover:text-primary-container transition-colors">Schedule a Drop-Off <span className="w-6 h-px bg-current"></span></span>
            </div>
          </a>
        </div>

        <div className="mt-16 md:mt-20 pt-10 border-t border-outline-variant/30 reveal">
          <div className="grid grid-cols-1 md:grid-cols-12 gap-8 md:gap-10 mb-8 items-end">
            <h3 className="md:col-span-4 font-label text-xs tracking-widest-custom uppercase text-primary-container border-l-2 border-primary-container pl-4">Also Performed In-House</h3>
            <p className="md:col-span-8 font-body text-sm text-on-surface-variant leading-relaxed">A complete catalog of supporting work, handled by the same technicians, under the same roof, to the same standard.</p>
          </div>
          <div className="flex flex-wrap gap-x-3 gap-y-3">
            {[
              'Paintless Dent Removal',
              'Alloy Wheel Refinishing',
              'Frame & Unibody Straightening',
              'Headlight Restoration',
              'Bumper Repair',
              'Plastic Welding',
              'Color Matching',
              'Detailing & Buff-Out',
              'Insurance Claim Coordination',
              'Complimentary Estimates',
              'Towing Assistance',
              'Loss-of-Use Coordination',
            ].map((s) => (
              <span key={s} className="font-label text-[10px] tracking-widest-custom uppercase text-on-surface-variant border border-outline-variant/40 px-4 py-2.5 hover:border-primary-container hover:text-primary-container transition-colors">
                {s}
              </span>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

function FacilityTour() {
  const tiles = [
    { src: IMG.reception, thumb: IMG.receptionThumb, label: 'Reception & Lobby', caption: 'Where every repair begins. Sit with an advisor at the GM-Certified Williamson Collision Center front counter.' },
    { src: IMG.shopOverview, thumb: IMG.shopOverviewThumb, label: 'Production Floor', caption: 'Multiple bays for structural and cosmetic work, executed under one roof.' },
    { src: IMG.frameRackCarOLiner, thumb: IMG.frameRackCarOLinerThumb, label: 'Frame Alignment Rack', caption: 'Car-O-Liner laser measuring system pulls frames back to exact factory tolerances.' },
    { src: IMG.paintMixRoom, thumb: IMG.paintMixRoomThumb, label: 'Paint Mixing Lab', caption: 'In-house spectrophotometer color match with a full refinish toner library.' },
    { src: IMG.escaladeMasked, thumb: IMG.escaladeMaskedThumb, label: 'Aluminum Repair Bay', caption: 'Isolated, contamination-free room with dedicated aluminum tooling.' },
    { src: IMG.teamWarehouse, thumb: IMG.teamWarehouseThumb, label: 'Parts Warehouse', caption: 'OEM inventory staged on-site so repairs never wait on a part.' },
    { src: IMG.serviceDrive, thumb: IMG.serviceDriveThumb, label: 'Covered Service Drive', caption: 'Climate-protected drop-off and intake. Your vehicle is sheltered from the moment it arrives.' },
    { src: IMG.paintBench, thumb: IMG.paintBenchThumb, label: 'Refinish Bench', caption: 'Multi-stage clear, environmental bake and detail prep. Every panel inspected before delivery.' },
    { src: IMG.escaladeBumper, thumb: IMG.escaladeBumperThumb, label: 'Panel Repair Bay', caption: 'OEM bumpers, fenders, hoods and quarters fit and sealed to factory drawings.' },
  ];
  const [active, setActive] = useState(0);
  // Full-size featured images mount on demand (first tile plus any the user
  // has viewed) instead of all nine loading up front.
  const [viewed, setViewed] = useState<Set<number>>(() => new Set([0]));
  const select = (i: number) => {
    setActive(i);
    setViewed((s) => (s.has(i) ? s : new Set(s).add(i)));
  };
  const current = tiles[active];
  const scrollerRef = useRef<HTMLDivElement>(null);

  const scrollByPage = (dir: -1 | 1) => {
    const el = scrollerRef.current;
    if (!el) return;
    const firstChild = el.firstElementChild as HTMLElement | null;
    if (!firstChild) return;
    const gap = parseFloat(getComputedStyle(el).columnGap || '16') || 16;
    const step = (firstChild.offsetWidth + gap) * 4;
    el.scrollBy({ left: dir * step, behavior: 'smooth' });
  };

  return (
    <section id="facility" data-tone="light" className="py-20 md:py-32 bg-paper relative">
      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 mb-12 md:mb-14 items-end">
          <div className="lg:col-span-7 reveal reveal-left">
            <p className="font-label text-xs tracking-widest-custom uppercase text-accent-deep mb-5 border-l-2 border-accent-deep pl-4">Inside the Shop</p>
            <h2 className="font-headline text-4xl md:text-6xl font-extrabold uppercase tracking-tighter text-ink leading-[0.95]">
              Built for <br/><span className="text-ink-muted">the Work.</span>
            </h2>
          </div>
          <p className="lg:col-span-5 font-body text-sm md:text-base text-ink-muted leading-relaxed pb-1 reveal reveal-delay-2">
            A purpose-built facility for collision repair, with covered service drives, climate-controlled prep bays, downdraft paint booths, a full in-house paint mixing lab, and a dedicated aluminum repair room. Every tool, every certification, on one property.
          </p>
        </div>

        {/* Featured carousel image */}
        <div className="relative h-[420px] md:h-[560px] overflow-hidden border border-paper-line shadow-2xl shadow-black/15 reveal" aria-live="polite">
          {tiles.map((t, i) =>
            viewed.has(i) ? (
              <img
                key={t.label}
                alt={`${t.label} at Williamson-Collision`}
                src={t.src}
                decoding="async"
                className={`absolute inset-0 w-full h-full object-cover transition-opacity duration-700 ease-out ${i === active ? 'opacity-100' : 'opacity-0'}`}
                aria-hidden={i !== active}
              />
            ) : null
          )}
          <div className="absolute inset-0 bg-gradient-to-t from-background/85 via-background/15 to-transparent pointer-events-none"></div>
          <div className="absolute inset-x-0 bottom-0 p-8 md:p-12 pointer-events-none">
            <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container flex items-center gap-3 mb-4">
              <span className="w-8 h-px bg-primary-container"></span>{String(active + 1).padStart(2, '0')} &nbsp;/&nbsp; {String(tiles.length).padStart(2, '0')}
            </span>
            <h3 className="font-headline text-3xl md:text-5xl font-extrabold uppercase tracking-tighter text-on-background leading-[0.95] mb-3">{current.label}</h3>
            <p className="font-body text-sm md:text-base text-on-surface-variant max-w-xl leading-relaxed">{current.caption}</p>
          </div>
        </div>

        {/* Thumbnail carousel: 4 visible per page, horizontal scroll for the rest */}
        <div className="mt-4 md:mt-5 relative">
          <div
            ref={scrollerRef}
            className="grid grid-flow-col auto-cols-[calc(50%-0.375rem)] md:auto-cols-[calc(25%-0.75rem)] gap-3 md:gap-4 overflow-x-auto snap-x snap-mandatory pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
          >
            {tiles.map((t, i) => {
              const isActive = i === active;
              return (
                <button
                  key={t.label}
                  type="button"
                  onClick={() => select(i)}
                  aria-label={`Show ${t.label}`}
                  aria-pressed={isActive}
                  className={`group relative h-[110px] md:h-[140px] overflow-hidden border text-left transition-all duration-500 snap-start ${isActive ? 'border-accent-deep shadow-lg shadow-black/15' : 'border-paper-line hover:border-accent-deep/60'}`}
                >
                  <img
                    alt=""
                    src={t.thumb}
                    aria-hidden="true"
                    loading="lazy"
                    decoding="async"
                    className={`absolute inset-0 w-full h-full object-cover transition-all duration-500 ${isActive ? 'opacity-100' : 'opacity-70 group-hover:opacity-95 group-hover:scale-105'}`}
                  />
                  <div className={`absolute inset-0 transition-colors duration-500 ${isActive ? 'bg-gradient-to-t from-background/65 via-transparent to-transparent' : 'bg-gradient-to-t from-background/65 via-background/15 to-transparent'}`}></div>
                  {isActive && <div className="absolute top-0 left-0 right-0 h-px bg-primary-container"></div>}
                  <div className="absolute inset-x-0 bottom-0 p-3 md:p-4">
                    <p className={`font-label text-[10px] tracking-widest-custom uppercase transition-colors duration-500 ${isActive ? 'text-primary-container' : 'text-on-surface-variant group-hover:text-on-background'}`}>
                      <span className="opacity-60 mr-2">{String(i + 1).padStart(2, '0')}</span>{t.label}
                    </p>
                  </div>
                </button>
              );
            })}
          </div>

          {tiles.length > 4 && (
            <>
              <button
                type="button"
                aria-label="Previous thumbnails"
                onClick={() => scrollByPage(-1)}
                className="hidden md:flex absolute -left-3 lg:-left-5 top-1/2 -translate-y-1/2 w-10 h-10 items-center justify-center bg-paper border border-paper-line text-ink hover:border-accent-deep hover:text-accent-deep transition-colors shadow-lg shadow-black/10"
              >
                <span className="material-symbols-outlined text-xl">chevron_left</span>
              </button>
              <button
                type="button"
                aria-label="Next thumbnails"
                onClick={() => scrollByPage(1)}
                className="hidden md:flex absolute -right-3 lg:-right-5 top-1/2 -translate-y-1/2 w-10 h-10 items-center justify-center bg-paper border border-paper-line text-ink hover:border-accent-deep hover:text-accent-deep transition-colors shadow-lg shadow-black/10"
              >
                <span className="material-symbols-outlined text-xl">chevron_right</span>
              </button>
            </>
          )}
        </div>
      </div>
    </section>
  );
}

function WaterbornePaint() {
  const advantages = [
    {
      num: '01',
      icon: 'palette',
      title: 'Color Accuracy',
      desc: 'Automakers build cars with waterborne basecoats, so a matching refinish system (the Sherwin-Williams Ultra 9K System) reproduces metallic flake orientation and factory color with flawless accuracy.',
    },
    {
      num: '02',
      icon: 'eco',
      title: 'Environmental & Safety Compliance',
      desc: 'Waterborne technology slashes toxic VOC emissions by up to 90% versus traditional solvent systems, clearing EPA VOC regulations and OSHA spray-finishing safety benchmarks with room to spare.',
    },
    {
      num: '03',
      icon: 'shield',
      title: 'Efficiency & Durability',
      desc: 'Higher solids content builds full opacity in fewer coats, yielding a thinner, more flexible, chip-resistant film that withstands extreme weather variations.',
    },
    {
      num: '04',
      icon: 'health_and_safety',
      title: 'Workplace Health',
      desc: 'Lower toxicity and flammability reduce painters’ chronic-exposure risk and shop fire hazards, and can help lower insurance premiums.',
    },
  ];

  return (
    <section data-tone="dark" className="py-20 md:py-32 bg-background relative overflow-hidden">
      <div className="absolute -top-24 right-0 w-[680px] h-[680px] bg-primary-container/10 rounded-full blur-[140px] pointer-events-none"></div>

      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12 relative z-10">
        {/* HEADER */}
        <div className="mb-14 md:mb-16 grid grid-cols-1 md:grid-cols-12 gap-8 md:gap-10 items-end">
          <div className="md:col-span-7 reveal">
            <p className="font-label text-xs tracking-widest-custom uppercase text-primary-container mb-5 border-l-2 border-primary-container pl-4">Refinish Technology</p>
            <h2 className="font-headline text-4xl md:text-6xl font-extrabold uppercase tracking-tighter text-on-background leading-[0.95]">
              Waterborne Paint.<br/><span className="text-on-surface-variant">Factory Finish.</span>
            </h2>
          </div>
          <p className="md:col-span-5 font-body text-sm md:text-base text-on-surface-variant max-w-md leading-relaxed pb-1 reveal reveal-delay-2">
            The world&apos;s leading automakers spray water-based basecoats on their factory assembly lines. Refinishing with the same technology is how we reproduce a true OEM finish: superior color match, higher durability, and dramatically lower emissions, in full regulatory compliance.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Feature image with the headline 90% VOC stat */}
          <div className="lg:col-span-5 group relative overflow-hidden border border-outline-variant/30 shadow-2xl shadow-black/40 min-h-[360px] lg:min-h-0 reveal">
            <img alt="In-house paint mixing room with the Sherwin-Williams Ultra 9K waterborne toner library" src={IMG.paintMixRoom} loading="lazy" decoding="async" className="absolute inset-0 w-full h-full object-cover opacity-90 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" />
            <div className="absolute inset-0 bg-gradient-to-t from-background/90 via-background/35 to-transparent"></div>
            <div className="absolute inset-x-0 bottom-0 p-8 md:p-10">
              <div className="font-headline text-6xl md:text-7xl font-extrabold tracking-tighter text-primary-container leading-none">90%</div>
              <div className="mt-3 font-label text-[10px] tracking-widest-custom uppercase text-on-surface-variant flex items-center gap-3">
                <span className="w-8 h-px bg-primary-container"></span>Lower VOC Emissions
              </div>
              <div className="mt-5 font-headline text-sm font-bold uppercase tracking-tight text-on-background">Sherwin-Williams Ultra 9K System</div>
            </div>
          </div>

          {/* Advantage cards */}
          <div className="lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-4 md:gap-6">
            {advantages.map((a, i) => (
              <div
                key={a.num}
                className="group relative bg-surface-container-lowest border border-outline-variant/30 p-7 md:p-8 hover:border-primary-container/50 transition-colors duration-500 reveal"
                style={{ transitionDelay: `${i * 0.08}s` }}
              >
                <div className="flex items-center justify-between mb-5">
                  <span className="material-symbols-outlined text-primary-container text-[28px]">{a.icon}</span>
                  <span className="font-label text-[10px] tracking-widest-custom uppercase text-outline-variant">{a.num}</span>
                </div>
                <h3 className="font-headline text-lg md:text-xl font-bold uppercase tracking-tight text-on-background mb-3 leading-[1.1]">{a.title}</h3>
                <p className="font-body text-xs md:text-sm text-on-surface-variant leading-relaxed">{a.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

function Process() {
  return (
    <section data-tone="dark" className="py-16 md:py-24 bg-background relative">
      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12">
        <div className="mb-16 reveal">
          <p className="font-label text-xs tracking-widest-custom uppercase text-primary-container mb-4 border-l-2 border-primary-container pl-4">The Williamson Automotive Standard</p>
          <h2 className="font-headline text-4xl md:text-5xl font-extrabold uppercase tracking-tighter text-on-background leading-tight">
            Factory-Certified <br/><span className="text-on-surface-variant">Repair Process</span>
          </h2>
          <p className="font-body text-sm text-on-surface-variant mt-6 max-w-2xl">
            A transparent, stage-gated process ensuring every repair uses genuine OEM parts and is executed to exact manufacturer specifications, so your vehicle leaves our facility as close to factory condition as engineering allows.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-10 md:gap-6 mt-12">
          {[
            { num: '01', title: 'Complimentary Estimate', desc: 'Comprehensive evaluation and effortless insurance claims coordination.' },
            { num: '02', title: 'Structural Alignment', desc: 'Laser-guided frame straightening returning the vehicle to exact factory tolerances.' },
            { num: '03', title: 'Refinishing', desc: 'Computerized color matching and multi-stage environmental baking for an OEM finish.' },
            { num: '04', title: 'Calibration & Delivery', desc: 'ADAS recalibration, rigorous QA inspection, ensuring true factory-spec operation.' },
          ].map((phase, i, arr) => (
            <div key={phase.num} className="group relative reveal" style={{ transitionDelay: `${i * 0.1}s` }}>
              <div className="flex items-center mb-6">
                <div className="w-12 h-12 flex items-center justify-center border border-outline-variant/40 bg-surface-container-low text-on-surface-variant font-headline font-bold text-sm tracking-widest-custom shrink-0 group-hover:border-primary-container group-hover:text-primary-container group-hover:bg-surface-container transition-colors duration-300">
                  {phase.num}
                </div>
                {i < arr.length - 1 && (
                  <div className="h-px flex-1 bg-outline-variant/30 ml-4 hidden md:block" aria-hidden="true"></div>
                )}
              </div>
              <p className="font-label text-xs tracking-widest-custom uppercase text-outline-variant mb-3 group-hover:text-on-background transition-colors">Phase {phase.num}</p>
              <h3 className="font-headline text-lg font-bold uppercase text-on-background mb-3 tracking-tight">{phase.title}</h3>
              <p className="font-body text-xs text-on-surface-variant leading-relaxed">{phase.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Team() {
  const paintTeam = {
    num: '01',
    src: IMG.paintShopStaff,
    alt: 'Williamson Collision Center paint and refinish team',
    name: 'Paint & Refinish',
    role: 'Color · Finish · Detail',
  };
  const sideTeam = [
    { num: '02', src: IMG.bodyTechStaff, alt: 'Williamson Collision Center body technician team in the production shop', name: 'Body Technicians', role: 'Aluminum & Structural' },
    { num: '03', src: IMG.officeStaff, alt: 'Williamson Collision Center office and service advisor staff at the front desk', name: 'Office & Advisors', role: 'Insurance & Estimates' },
  ];

  return (
    <section id="team" data-tone="light" className="py-20 md:py-32 bg-paper relative overflow-hidden">
      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 mb-12 md:mb-14 items-end">
          <div className="lg:col-span-7 reveal">
            <p className="font-label text-xs tracking-widest-custom uppercase text-accent-deep mb-5 border-l-2 border-accent-deep pl-4">The People</p>
            <h2 className="font-headline text-4xl md:text-6xl font-extrabold uppercase tracking-tighter text-ink leading-[0.95]">
              Factory-Trained.<br/><span className="text-ink-muted">Locally Rooted.</span>
            </h2>
          </div>
          <div className="lg:col-span-5 reveal reveal-delay-2">
            <p className="font-body text-sm md:text-base text-ink-muted leading-relaxed mb-6">
              Many of our technicians have been with the Williamson family for over a decade. Every team member, from the service advisors at the front counter to the body techs in the booth, is OEM-trained and continuously certified on the latest manufacturer procedures.
            </p>
            <a href={CARWISE_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-3 font-headline text-sm font-bold uppercase tracking-widest-custom text-accent-deep hover:text-ink transition-colors">
              Meet us in person
              <span className="material-symbols-outlined text-base">arrow_forward</span>
            </a>
          </div>
        </div>

        {/* Mixed-orientation editorial layout: the tall paint-shop group photo anchors the
            left as a full-height portrait, with the two landscape group photos stacked beside it. */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-6">
          {/* Tall portrait: Paint & Refinish team */}
          <div className="group relative md:col-span-5 overflow-hidden border border-paper-line shadow-2xl shadow-black/15 reveal aspect-[4/5] md:aspect-auto md:min-h-[640px]">
            <img alt={paintTeam.alt} src={paintTeam.src} loading="lazy" decoding="async" className="absolute inset-0 w-full h-full object-cover object-center opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" />
            {/* Caption scrim stays dark so white text remains readable over varied photos */}
            <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/15 to-transparent"></div>
            <div className="absolute inset-x-0 bottom-0 p-6 md:p-8">
              <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container flex items-center gap-3 mb-4">
                <span className="w-6 h-px bg-primary-container"></span>{paintTeam.num}
              </span>
              <h3 className="font-headline text-2xl md:text-3xl font-bold uppercase tracking-tight text-white leading-[1.05] mb-2">{paintTeam.name}</h3>
              <p className="font-label text-[10px] tracking-widest-custom uppercase text-white/75">{paintTeam.role}</p>
            </div>
          </div>

          {/* Two stacked landscape group photos */}
          <div className="md:col-span-7 grid grid-rows-1 md:grid-rows-2 gap-4 md:gap-6">
            {sideTeam.map((m, i) => (
              <div
                key={m.num}
                className="group relative overflow-hidden border border-paper-line shadow-2xl shadow-black/15 reveal aspect-[16/10] md:aspect-auto"
                style={{ transitionDelay: `${(i + 1) * 0.08}s` }}
              >
                <img alt={m.alt} src={m.src} loading="lazy" decoding="async" className="absolute inset-0 w-full h-full object-cover object-center opacity-100 group-hover:scale-105 transition-all duration-700 ease-out" />
                <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/15 to-transparent"></div>
                <div className="absolute inset-x-0 bottom-0 p-6 md:p-7">
                  <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container flex items-center gap-3 mb-4">
                    <span className="w-6 h-px bg-primary-container"></span>{m.num}
                  </span>
                  <h3 className="font-headline text-xl md:text-2xl font-bold uppercase tracking-tight text-white leading-[1.05] mb-2">{m.name}</h3>
                  <p className="font-label text-[10px] tracking-widest-custom uppercase text-white/75">{m.role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

function InsurancePartners() {
  const carriers = [
    'State Farm Select Service®',
    'USAA STARS',
    'Travelers',
    'STAR Casualty',
    'United Automotive',
    'Direct General',
    'Hanover',
    'Liberty Mutual',
  ];
  const logistics = [
    'Direct Insurance Billing',
    'On-Site Enterprise Rent-A-Car',
    'Loss-of-Use Coordination',
    'Towing Network',
    'All Major Carriers Accepted',
  ];
  return (
    <section data-tone="dark" className="py-16 md:py-20 bg-background border-t border-outline-variant/20">
      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12 items-start">
          <div className="reveal reveal-left">
            <p className="font-label text-xs tracking-widest-custom uppercase text-primary-container mb-4 border-l-2 border-primary-container pl-4">Insurance &amp; Logistics</p>
            <h2 className="font-headline text-2xl font-bold uppercase tracking-tight text-on-background leading-tight">
              We handle the paperwork. <span className="text-on-surface-variant">You drive away.</span>
            </h2>
          </div>
          <div className="md:col-span-2 reveal reveal-right">
            {/* Direct repair program & preferred carriers */}
            <h3 className="font-label text-[10px] tracking-widest-custom uppercase text-on-surface-variant mb-4">Direct Repair &amp; Preferred Carriers</h3>
            <div className="flex flex-wrap gap-x-3 gap-y-3 mb-10">
              {carriers.map((c) => (
                <span key={c} className="font-label text-[10px] tracking-widest-custom uppercase text-on-surface-variant border border-outline-variant/40 px-4 py-2.5 hover:border-primary-container hover:text-primary-container transition-colors">
                  {c}
                </span>
              ))}
            </div>

            {/* Logistics & convenience */}
            <h3 className="font-label text-[10px] tracking-widest-custom uppercase text-on-surface-variant mb-4">Logistics &amp; Convenience</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-3">
              {logistics.map((p) => (
                <div key={p} className="flex items-start gap-3 border-l-2 border-outline-variant/40 pl-4 py-2 hover:border-primary-container transition-colors">
                  <span className="material-symbols-outlined text-primary-container text-base mt-0.5">check_circle</span>
                  <span className="font-body text-sm text-on-background">{p}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function WeAreHere() {
  return (
    <section data-tone="dark" className="relative w-full bg-background overflow-hidden">
      <div className="grid grid-cols-1 lg:grid-cols-12 min-h-[260px]">
        {/* Vehicle image fades into the dark from the right */}
        <div className="relative lg:col-span-5 h-[200px] lg:h-auto">
          <img
            src={IMG.frameRackWide}
            alt="Cadillac on the lift inside the Williamson-Collision shop"
            loading="lazy"
            decoding="async"
            className="absolute inset-0 w-full h-full object-cover object-left"
          />
          {/* Horizontal fade to the right edge so the image bleeds into the dark CTA column */}
          <div className="absolute inset-0 bg-gradient-to-r from-background/15 via-background/35 to-background"></div>
          {/* Subtle bottom fade for mobile layout */}
          <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent lg:hidden"></div>
        </div>

        {/* CTA content */}
        <div className="lg:col-span-7 bg-background flex flex-col justify-center gap-10 md:gap-12 px-5 sm:px-8 md:px-12 lg:px-16 py-14 md:py-16 lg:py-20">
          <div className="reveal">
            <p className="font-label text-xs tracking-widest-custom uppercase text-primary-container mb-4 border-l-2 border-primary-container pl-4">Ready to get started?</p>
            <h2 className="font-headline text-4xl md:text-5xl lg:text-6xl font-extrabold uppercase tracking-tighter text-on-background leading-[0.95]">
              We&apos;re Here<br/><span className="text-on-surface-variant">to Help.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 md:gap-5 reveal reveal-delay-2">
            <a
              href="tel:+13052388801"
              className="group flex flex-col justify-between gap-8 p-6 md:p-7 border border-outline-variant/30 hover:border-primary-container transition-colors duration-500 min-h-[150px]"
            >
              <div className="flex items-start justify-between gap-4">
                <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container flex items-center gap-2"><span className="w-6 h-px bg-primary-container"></span>Call</span>
                <span className="material-symbols-outlined text-on-surface-variant group-hover:text-primary-container transition-colors">call</span>
              </div>
              <div className="font-headline text-xl md:text-2xl font-bold tracking-tight text-on-background group-hover:text-primary-container transition-colors leading-tight">305-238-8801</div>
            </a>

            <a
              href={CARWISE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="group flex flex-col justify-between gap-8 p-6 md:p-7 border border-outline-variant/30 hover:border-primary-container transition-colors duration-500 min-h-[150px]"
            >
              <div className="flex items-start justify-between gap-4">
                <span className="font-label text-[10px] tracking-widest-custom uppercase text-primary-container flex items-center gap-2"><span className="w-6 h-px bg-primary-container"></span>Visit</span>
                <span className="material-symbols-outlined text-on-surface-variant group-hover:text-primary-container transition-colors">event</span>
              </div>
              <div className="font-headline text-xl md:text-2xl font-bold tracking-tight text-on-background group-hover:text-primary-container transition-colors leading-tight">Schedule Appointment</div>
            </a>

            <a
              href={CARWISE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="group flex flex-col justify-between gap-8 p-6 md:p-7 bg-primary-container text-on-primary-container hover:bg-white transition-colors duration-500 min-h-[150px]"
            >
              <div className="flex items-start justify-between gap-4">
                <span className="font-label text-[10px] tracking-widest-custom uppercase opacity-70 flex items-center gap-2"><span className="w-6 h-px bg-current"></span>Estimate</span>
                <span className="material-symbols-outlined">arrow_forward</span>
              </div>
              <div className="font-headline text-xl md:text-2xl font-bold tracking-tight leading-tight">Get an Estimate</div>
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}

function Location() {
  return (
    <section id="location" data-tone="light" className="py-16 md:py-24 bg-paper border-t border-paper-line">
      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className="reveal reveal-left">
            <h2 className="font-headline text-3xl font-bold uppercase tracking-tighter text-ink mb-6">Williamson Automotive Collision Center</h2>
            <p className="font-body text-sm text-ink-muted mb-8 max-w-md">
              Our state-of-the-art repair and restoration facility in South Miami is engineered to provide an unparalleled service experience.
            </p>

            <div className="space-y-8 bg-paper-card p-8 border border-paper-line">
              <div>
                <h3 className="font-label text-xs tracking-widest-custom uppercase text-ink-faint mb-2">Address</h3>
                <p className="font-headline text-lg tracking-tight text-ink">19300 SW 108 Ave<br/>Miami, FL 33157</p>
              </div>

              <div>
                <h3 className="font-label text-xs tracking-widest-custom uppercase text-ink-faint mb-2">Hours of Operation</h3>
                <ul className="text-sm font-body text-ink-muted space-y-2">
                  {[
                    ['Monday', '7:30 AM - 5:00 PM'],
                    ['Tuesday', '7:30 AM - 5:00 PM'],
                    ['Wednesday', '7:30 AM - 5:00 PM'],
                    ['Thursday', '7:30 AM - 5:00 PM'],
                    ['Friday', '7:30 AM - 5:00 PM'],
                    ['Saturday', '8:00 AM - 12:00 PM'],
                  ].map(([day, hrs]) => (
                    <li key={day} className="flex justify-between border-b border-paper-line pb-2">
                      <span>{day}</span>
                      <span className="text-ink font-medium">{hrs}</span>
                    </li>
                  ))}
                  <li className="flex justify-between text-ink-faint">
                    <span>Sunday</span>
                    <span>Closed</span>
                  </li>
                </ul>
              </div>

              <div className="grid grid-cols-2 gap-6">
                <div>
                  <h3 className="font-label text-xs tracking-widest-custom uppercase text-ink-faint mb-2">Body Shop</h3>
                  <a href="tel:+13052388801" className="font-headline text-xl text-accent-deep hover:text-ink transition-colors">305-238-8801</a>
                </div>
                <div>
                  <h3 className="font-label text-xs tracking-widest-custom uppercase text-ink-faint mb-2">Enterprise (On-Site)</h3>
                  <a href="tel:+13052561112" className="font-headline text-xl text-ink hover:text-accent-deep transition-colors">305-256-1112</a>
                </div>
              </div>
            </div>
          </div>

          <div className="reveal reveal-right reveal-delay-2 flex flex-col gap-4">
            <div className="relative h-[320px] overflow-hidden border border-paper-line">
              <img alt="Williamson Collision Center building exterior with signage" src={IMG.facadeFront} loading="lazy" decoding="async" className="w-full h-full object-cover" />
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/55 to-transparent p-5">
                <span className="font-label text-[10px] tracking-widest-custom uppercase text-white">Look for the Cadillac &middot; GMC &middot; Buick signage</span>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="relative h-[260px] overflow-hidden border border-paper-line">
                <img alt="Aerial view of the Williamson Collision Center property in South Miami" src={IMG.facadeAerial} loading="lazy" decoding="async" className="w-full h-full object-cover" />
                <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/55 to-transparent p-4">
                  <span className="font-label text-[10px] tracking-widest-custom uppercase text-white">Aerial &middot; Full-Property View</span>
                </div>
              </div>
              <div className="h-[260px] w-full border border-paper-line bg-paper-card p-2">
                <iframe
                  title="Williamson Collision Center Location Map"
                  width="100%"
                  height="100%"
                  style={{ border: 0 }}
                  loading="lazy"
                  allowFullScreen
                  referrerPolicy="no-referrer-when-downgrade"
                  src="https://maps.google.com/maps?q=Williamson+Cadillac+19300+SW+108+Ave+Miami+FL+33157&z=15&output=embed"
                ></iframe>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// NOTE: keep these questions/answers in sync with the FAQPage JSON-LD in index.html.
const FAQ_ITEMS = [
  {
    q: 'Do I have to use the shop my insurance company recommends?',
    a: 'No. Florida law gives you the right to choose who repairs your vehicle — your insurer cannot require you to use a specific shop. Bring your claim to us and we’ll coordinate directly with your carrier from the first estimate to final delivery.',
  },
  {
    q: 'Do you repair all makes and models?',
    a: 'Yes. We hold factory certifications for more than 15 brands — including GM, Stellantis, Hyundai, Kia, Nissan, and Infiniti — and every other make is repaired in the same facility, by the same OEM-trained technicians, to the same standard.',
  },
  {
    q: 'Will you handle my insurance claim?',
    a: 'Yes. We’re a direct repair partner for carriers including State Farm Select Service and USAA STARS, and we work with all major insurers. We handle the estimates, supplements, photos, and direct billing so you don’t have to.',
  },
  {
    q: 'Can I get a rental car while my vehicle is repaired?',
    a: 'Yes — Enterprise Rent-A-Car operates a counter right on our property. Drop your keys with an advisor and drive out in a rental, with insurance direct billing available.',
  },
  {
    q: 'How long will my repair take?',
    a: 'It depends on the extent of the damage and parts availability. You’ll get a time estimate up front, we stage OEM parts on-site before work begins, and your advisor keeps you updated at every stage of the repair.',
  },
  {
    q: 'How do I get an estimate?',
    a: 'Estimates are complimentary. Schedule online through our CARWISE profile or call 305-238-8801 — we’re open Monday through Friday 7:30 AM to 5 PM and Saturday 8 AM to noon.',
  },
];

function Faq() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <section id="faq" data-tone="light" className="py-20 md:py-32 bg-paper border-t border-paper-line">
      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-14">
          <div className="lg:col-span-5 reveal reveal-left">
            <p className="font-label text-xs tracking-widest-custom uppercase text-accent-deep mb-5 border-l-2 border-accent-deep pl-4">Common Questions</p>
            <h2 className="font-headline text-4xl md:text-6xl font-extrabold uppercase tracking-tighter text-ink leading-[0.95] mb-6">
              Answers,<br/><span className="text-ink-muted">Up Front.</span>
            </h2>
            <p className="font-body text-sm md:text-base text-ink-muted leading-relaxed max-w-md mb-8">
              The questions we hear most at the front counter. Anything we didn&apos;t cover, call us at{' '}
              <a href="tel:+13052388801" className="text-accent-deep hover:text-ink transition-colors font-medium">305-238-8801</a>{' '}
              and an advisor will walk you through it.
            </p>
            <a href={CARWISE_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-3 font-headline text-sm font-bold uppercase tracking-widest-custom text-accent-deep hover:text-ink transition-colors">
              Get an Estimate
              <span className="material-symbols-outlined text-base">arrow_forward</span>
            </a>
          </div>

          <div className="lg:col-span-7 reveal reveal-right border-t border-paper-line">
            {FAQ_ITEMS.map((item, i) => (
              <div key={item.q} className="border-b border-paper-line">
                <button
                  type="button"
                  onClick={() => setOpen(open === i ? null : i)}
                  aria-expanded={open === i}
                  className="w-full flex items-center justify-between gap-6 py-5 md:py-6 text-left group cursor-pointer"
                >
                  <span className="font-headline text-base md:text-lg font-bold uppercase tracking-tight text-ink group-hover:text-accent-deep transition-colors">{item.q}</span>
                  <span className={`material-symbols-outlined text-accent-deep shrink-0 transition-transform duration-300 ${open === i ? 'rotate-45' : ''}`}>add</span>
                </button>
                <div className={`grid transition-all duration-500 ease-in-out ${open === i ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'}`}>
                  <div className="overflow-hidden">
                    <p className="font-body text-sm md:text-base text-ink-muted leading-relaxed max-w-2xl pb-6">{item.a}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

// Persistent tap-to-call button for phones: the page's job is to generate
// calls, so the number stays reachable after the navbar scrolls away.
function MobileCallButton() {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const onScroll = () => setShow(window.scrollY > 600);
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  return (
    <a
      href="tel:+13052388801"
      aria-label="Call Williamson Collision Center at 305-238-8801"
      className={`fixed bottom-5 right-5 z-40 md:hidden inline-flex items-center gap-2 px-5 py-4 bg-primary-container text-on-primary-container font-headline font-bold uppercase tracking-widest-custom text-xs shadow-2xl shadow-black/50 transition-all duration-500 ${show ? 'translate-y-0 opacity-100' : 'translate-y-24 opacity-0 pointer-events-none'}`}
    >
      <span className="material-symbols-outlined text-lg">call</span>
      Call Us
    </a>
  );
}

function Footer() {
  const quickLinks = [
    { label: 'Home', href: '#' },
    { label: 'About Us', href: '#team' },
    { label: 'Services', href: '#services' },
    { label: 'Certifications', href: '#certifications' },
    { label: 'Why Choose Us', href: '#facility' },
    { label: 'FAQs', href: '#faq' },
    { label: 'Contact Us', href: '#location' },
  ];
  const services = [
    { label: 'Collision Repair', href: '#services' },
    { label: 'Paint & Refinishing', href: '#services' },
    { label: 'Frame Straightening', href: '#services' },
    { label: 'ADAS Calibration', href: '#services' },
    { label: 'Insurance Assistance', href: '#services' },
    { label: 'Rental Assistance', href: '#services' },
  ];

  return (
    <footer className="bg-paper border-t border-paper-line">
      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12 pt-14 md:pt-16 pb-10">
        <div className="grid grid-cols-1 md:grid-cols-12 gap-10 md:gap-8">
          {/* Brand */}
          <div className="md:col-span-4">
            <a href="#" aria-label="Williamson Automotive Collision Center home" className="inline-flex items-center overflow-hidden h-32 md:h-40">
              <img
                src={LOGO.brandBlack}
                alt="Williamson Automotive Collision Center"
                className="h-48 md:h-60 w-auto object-contain object-left"
                loading="lazy"
              />
            </a>
            <div className="mt-4 font-label text-[10px] tracking-widest-custom uppercase text-accent-deep">
              The Body Shop of Williamson Automotive
            </div>
            <p className="mt-3 font-body text-sm text-ink-muted leading-relaxed max-w-xs">
              Proudly serving Miami and the surrounding communities with the certified collision repair you expect from the Williamson Automotive name.
            </p>
            <div className="mt-6 flex gap-3">
              <a href="https://www.facebook.com/williamsoncadillacbuickgmc" target="_blank" rel="noopener noreferrer" aria-label="Facebook" className="w-9 h-9 rounded-full border border-paper-line flex items-center justify-center text-ink-muted hover:text-accent-deep hover:border-accent-deep transition-colors">
                <svg viewBox="0 0 24 24" fill="currentColor" className="w-4 h-4" aria-hidden="true">
                  <path d="M13.5 21v-7.125h2.49l.373-2.892H13.5V9.142c0-.836.232-1.406 1.432-1.406h1.53V5.151a20.5 20.5 0 0 0-2.231-.114c-2.207 0-3.719 1.347-3.719 3.822v2.124H8v2.892h2.512V21h2.988z"/>
                </svg>
              </a>
              <a href="https://www.instagram.com/williamsoncadillacbuickgmc/" target="_blank" rel="noopener noreferrer" aria-label="Instagram" className="w-9 h-9 rounded-full border border-paper-line flex items-center justify-center text-ink-muted hover:text-accent-deep hover:border-accent-deep transition-colors">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="w-4 h-4" aria-hidden="true">
                  <rect x="3" y="3" width="18" height="18" rx="5" ry="5"/>
                  <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/>
                  <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"/>
                </svg>
              </a>
              <a href="https://www.tiktok.com/@wagcadillacbuickgmc" target="_blank" rel="noopener noreferrer" aria-label="TikTok" className="w-9 h-9 rounded-full border border-paper-line flex items-center justify-center text-ink-muted hover:text-accent-deep hover:border-accent-deep transition-colors">
                <svg viewBox="0 0 24 24" fill="currentColor" className="w-4 h-4" aria-hidden="true">
                  <path d="M16.6 5.82A4.28 4.28 0 0 1 15.54 3h-3.09v12.4a2.59 2.59 0 0 1-2.59 2.5 2.6 2.6 0 0 1-2.6-2.6c0-1.72 1.66-3.01 3.37-2.48V9.66c-3.45-.46-6.47 2.22-6.47 5.64a5.67 5.67 0 0 0 5.69 5.7c3.14 0 5.69-2.55 5.69-5.7V9.01a7.35 7.35 0 0 0 4.3 1.38V7.3a4.36 4.36 0 0 1-3.24-1.48z"/>
                </svg>
              </a>
            </div>
          </div>

          {/* Quick Links */}
          <div className="md:col-span-2">
            <h4 className="font-headline text-sm font-bold uppercase tracking-tight text-ink mb-5">Quick Links</h4>
            <ul className="space-y-3">
              {quickLinks.map((l) => (
                <li key={l.label}>
                  <a href={l.href} className="font-body text-sm text-ink-muted hover:text-accent-deep transition-colors">{l.label}</a>
                </li>
              ))}
            </ul>
          </div>

          {/* Services */}
          <div className="md:col-span-3">
            <h4 className="font-headline text-sm font-bold uppercase tracking-tight text-ink mb-5">Services</h4>
            <ul className="space-y-3">
              {services.map((s) => (
                <li key={s.label}>
                  <a href={s.href} className="font-body text-sm text-ink-muted hover:text-accent-deep transition-colors">{s.label}</a>
                </li>
              ))}
            </ul>
          </div>

          {/* Contact Us */}
          <div className="md:col-span-3">
            <h4 className="font-headline text-sm font-bold uppercase tracking-tight text-ink mb-5">Contact Us</h4>
            <ul className="space-y-4">
              <li className="flex items-start gap-3">
                <span className="material-symbols-outlined text-[20px] text-accent-deep shrink-0 mt-px">place</span>
                <span className="font-body text-sm text-ink-muted leading-relaxed">
                  19300 SW 108 Ave<br/>Miami, FL 33157
                </span>
              </li>
              <li className="flex items-start gap-3">
                <span className="material-symbols-outlined text-[20px] text-accent-deep shrink-0 mt-px">call</span>
                <a href="tel:+13052388801" className="font-body text-sm text-ink-muted hover:text-accent-deep transition-colors">305-238-8801</a>
              </li>
              <li className="flex items-start gap-3">
                <span className="material-symbols-outlined text-[20px] text-accent-deep shrink-0 mt-px">mail</span>
                <a href="mailto:info@williamsoncollision.com" className="font-body text-sm text-ink-muted hover:text-accent-deep transition-colors break-all">info@williamsoncollision.com</a>
              </li>
              <li className="flex items-start gap-3">
                <span className="material-symbols-outlined text-[20px] text-accent-deep shrink-0 mt-px">schedule</span>
                <div className="font-body text-sm text-ink-muted leading-relaxed">
                  <div>Mon - Fri: 7:30 AM - 5:00 PM</div>
                  <div>Sat: 8:00 AM - 12:00 PM</div>
                  <div>Sun: Closed</div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* Bottom strip */}
      <div className="border-t border-paper-line">
        <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-12 py-5 flex flex-col md:flex-row justify-between items-center gap-3">
          <p className="font-body text-xs text-ink-muted">© 2026 Williamson Automotive Collision Center. All Rights Reserved.</p>
          <div className="flex gap-6">
            <a href="https://www.williamsoncadillac.com/privacy-policy" target="_blank" rel="noopener noreferrer" className="font-body text-xs text-ink-muted hover:text-accent-deep transition-colors">Privacy Policy</a>
            <a href={`${import.meta.env.BASE_URL}sitemap.xml`} target="_blank" rel="noopener noreferrer" className="font-body text-xs text-ink-muted hover:text-accent-deep transition-colors">Sitemap</a>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default function App() {
  useScrollReveal();
  return (
    <div className="min-h-screen flex flex-col antialiased bg-paper text-ink selection:bg-primary-container selection:text-on-primary-container">
      <Navbar />
      <main className="flex-grow">
        <Hero />
        <BrandStrip />
        <ServicesBento />
        <FacilityTour />
        <WaterbornePaint />
        <Process />
        <Team />
        <InsurancePartners />
        <Faq />
        <Location />
        <WeAreHere />
      </main>
      <Footer />
      <MobileCallButton />
    </div>
  );
}
